org: noteaid
app: noteaid-agent-example-1
service: noteaid-agent-example-1
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  agent:
    handler: __init__.handler
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4680
