org: noteaid
app: noteaid-agent
service: noteaid-agent-example-1
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10

functions:
  hello:
    handler: __init__.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-python-requirements
