org: noteaid
app: noteaid-agent
service: noteaid-agent-example-1
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.10
  timeout: 60

functions:
  agent:
    handler: __init__.handler
    timeout: 60
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-python-requirements
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 4680
